### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by AnzhiZhang** [ShaBaiTianCN/Chroma-Technology-2#15]
@FENGZI123L 
![2UI%N7E%P){T}GCP{M~F_A4](https://user-images.githubusercontent.com/37402126/169026107-dde60fa9-113d-45ab-aeef-403777f471fd.png)
![P GCOCOJY78Q_E(OQS~}HY](https://user-images.githubusercontent.com/37402126/169026115-715bd930-aca4-4b81-b7b3-e33f499068e9.png)
![E~%@G 9G)4TU1}VKWKDPWE](https://user-images.githubusercontent.com/37402126/169026122-29baa26b-6029-46d3-8347-ee18dc0cec12.png)

**Comment by Cactusstudent** [comment]
详见pr#16，已确认为法力
