### ISSUE TITLE
资源蜜蜂任务数值

### ISSUE THREAD

**Issue by AnzhiZhang** [ShaBaiTianCN/Chroma-Technology-2#6]
https://github.com/ShaBaiTianCN/Chroma-Technology-2/blob/ed75866f4bb93f922b538900ed812711a5bdd0c0/config/ftbquests/quests/chapters/poductive_bee.snbt#L33

@nai200

> 百科和游戏内说39%

_Originally posted by @AnzhiZhang in https://github.com/ShaBaiTianCN/Chroma-Technology-2/pull/1#discussion_r868766636_

**Comment by Cactusstudent** [comment]
找了半个小时，放弃了，游戏说啥就是什么吧……

**Comment by Cactusstudent** [comment]
不排除有作者魔改的风险
